language: java
jdk:
  - openjdk14
  -
before_install:
  - chmod + x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    recipients:
      -d.krylovk@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN='77fbb32c-bb58-49f3-86e7-279e52e04949'