server:
  port: 8080


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
    password: 132197
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  liquibase:
    change-log: classpath:db/changelog/db.changeLog-master.xml